apiVersion: v1
kind: Template
metadata:
  name: oc-pipeline
labels:
  application: oc-pipeline
parameters:
  - name: APP_ID
    description: Application
    displayName: Application
    required: true
  - name: NAMESPACE
    description: Namespace
    displayName: Namespace
    required: true
  - name: SCM
    description: SCM
    displayName: SCM
    required: true
  - name: SCM_COMMIT
    description: SCM Commit
    displayName: SCM Commit
    required: true
    value: master
  - name: APP_PORT
    description: Port
    displayName: Port
    required: true
    value: '8080'
  - name: DOMAIN
    description: Cluster Domain
    displayName: Cluster Domain
    required: true
  - name: BUILDER
    description: Application Builder Image
    displayName: Application Builder Image
    required: true
    value: 'cf-builder:latest'
  - name: APP_REPLICA
    description: Number of app instances
    displayName: Number of app instances
    required: true
    value: '1'
  - name: GIT_SSH_KEY
    description: GIT SSH private key
    displayName: GIT SSH private key
    required: true
    value: null
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ${APP_ID}
      namespace: ${NAMESPACE}
      labels:
        app: ${APP_ID}
    spec:
      strategy:
        type: Rolling
        rollingParams:
          updatePeriodSeconds: 1
          intervalSeconds: 1
          timeoutSeconds: 600
          maxUnavailable: 25%
          maxSurge: 25%
        resources: {}
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${APP_ID}
            from:
              kind: ImageStreamTag
              namespace: ${NAMESPACE}
              name: '${APP_ID}:latest'
        - type: ConfigChange
      replicas: ${APP_REPLICA}
      test: false
      selector:
        deploymentconfig: ${APP_ID}
      template:
        metadata:
          labels:
            app: ${APP_ID}
            deploymentconfig: ${APP_ID}
        spec:
          containers:
            - name: ${APP_ID}
              ports:
                - containerPort: ${APP_PORT}
                  protocol: TCP
              resources: {}
              terminationMessagePath: /dev/termination-log
              imagePullPolicy: Always
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: ${APP_ID}
      namespace: ${NAMESPACE}
      labels:
        app: ${APP_ID}
    spec:
      triggers:
        - type: ImageChange
          imageChange:
            lastTriggeredImageID: docker-registry-default.${DOMAIN}:5000/openshift/cf-builder:latest
        - type: ConfigChange
      runPolicy: Serial
      source:
        type: Git
        git:
          uri: '${SCM}'
          ref: ${SCM_COMMIT}
        sourceSecret: ${APP_ID}
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            namespace: tools
            name: '${BUILDER}'
      output:
        to:
          kind: ImageStreamTag
          name: '${APP_ID}:latest'
      resources: {}
      postCommit: {}
      nodeSelector: null
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: ${APP_ID}
      namespace: ${NAMESPACE}
    spec: {}
  - apiVersion: v1
    kind: Service
    metadata:
      name: ${APP_ID}
      namespace: ${NAMESPACE}
      labels:
        app: ${APP_ID}
    spec:
      ports:
        - name: ${APP_ID}-${APP_PORT}-tcp
          protocol: TCP
          port: ${{APP_PORT}}
          targetPort: ${{APP_PORT}}
      selector:
        deploymentconfig: ${APP_ID}
      type: ClusterIP
      sessionAffinity: None
  - apiVersion: v1
    kind: Route
    metadata:
      name: ${APP_ID}
      namespace: ${NAMESPACE}
      labels:
        app: ${APP_ID}
    spec:
      host: ${APP_ID}.${DOMAIN}
      to:
        kind: Service
        name: ${APP_ID}
        weight: 100
      port:
        targetPort: ${APP_ID}-${APP_PORT}-tcp
      tls:
        termination: edge
      wildcardPolicy: None
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${APP_ID}
      namespace: ${NAMESPACE}
    data:
      ssh-privatekey: ${GIT_SSH_KEY}
    type: kubernetes.io/ssh-auth
