---
name: datahub-omis-fe
namespace: datahub
scm: git@github.com:uktrade/omis-frontend.git
environments:
  - environment: dev
    type: gds
    app: dit-staging/dev-datahub/datahub-omis-dev
    vars:
      - API_ROOT: https://datahub-api-dev.cloudapps.digital
    secrets: true
    run: []
  - environment: uat
    type: gds
    app: dit-staging/uat-datahub/datahub-omis-uat
    vars:
      - API_ROOT: https://datahub-api-uat.cloudapps.digital
    secrets: true
    run: []
  - environment: demo
    type: gds
    app: dit-staging/dev-datahub/datahub-omis-demo
    vars:
      - API_ROOT: https://datahub-api-demo.cloudapps.digital
    secrets: true
    run: []
  - environment: staging
    type: gds
    app: dit-staging/staging-datahub/datahub-omis-staging
    vars:
      - API_ROOT: https://datahub-api-staging.cloudapps.digital
    secrets: true
    run: []
  - environment: production
    type: gds
    app: dit-services/datahub/datahub-omis
    vars:
      - API_ROOT: https://datahub-api.cloudapps.digital
    secrets: true
    run: []
