---
name: data-hub-filebrowser
namespace: datahub
scm: git@github.com:uktrade/data-hub-file-browser.git
environments:
  - environment: dev
    type: gds
    app: dit-staging/dev-datahub/data-hub-filebrowser-dev
    vars:
      - DISABLE_COLLECTSTATIC: 1
    secrets: true
    run:
      - "true"
  - environment: demo
    type: gds
    app: dit-staging/dev-datahub/data-hub-filebrowser-demo
    vars:
      - DISABLE_COLLECTSTATIC: 1
    secrets: true
    run:
      - "true"
  - environment: uat
    type: gds
    app: dit-staging/uat-datahub/data-hub-filebrowser-uat
    vars:
      - DISABLE_COLLECTSTATIC: 1
    secrets: true
    run:
      - "true"
  - environment: staging
    type: gds
    app: dit-staging/staging-datahub/data-hub-filebrowser-staging
    vars:
      - DISABLE_COLLECTSTATIC: 1
    secrets: true
    run:
      - "true"
  - environment: prod
    type: gds
    app: dit-services/datahub/data-hub-filebrowser
    vars:
      - DISABLE_COLLECTSTATIC: 1
    secrets: true
    run:
      - "true"
