---
name: directory-ui-export-readiness
namespace: directory
scm: git@github.com:uktrade/directory-ui-export-readiness.git
environments:
  - environment: dev
    type: gds
    app: dit-staging/dev-directory/directory-ui-export-readiness-dev
    vars:
      - DISABLE_COLLECTSTATIC: 0
    secrets: true
    run:
      - "true"
  - environment: staging
    type: gds
    app: dit-staging/staging-directory/directory-ui-export-readiness-stage
    vars:
      - DISABLE_COLLECTSTATIC: 0
    secrets: true
    run:
      - "true"
  - environment: prod
    type: gds
    app: dit-services/directory/directory-ui-export-readiness-prod
    vars:
      - DISABLE_COLLECTSTATIC: 0
    secrets: true
    run:
      - "true"
