---
name: exportwins-mi
namespace: mi
scm: git@github.com:uktrade/export-wins-ui-mi.git
environments:
  - environment: dev
    type: gds
    app: dit-staging/dev-mi/exportwins-mi-dev
    vars: []
    secrets: true
    run: []
  - environment: staging
    type: gds
    app: dit-staging/dev-staging/exportwins-mi-staging
    vars: []
    secrets: true
    run: []
  - environment: prod
    type: gds
    app: dit-services/mi/exportwins-mi
    vars: []
    secrets: true
    run: []
