---
name: export-opportunities-worker
namespace: exopps
scm: git@github.com:uktrade/export-opportunities.git
environments:
  - environment: continuous-deployment
    type: gds
    app: dit-staging/dev-exopps/export-opportunities-worker-continuous-deployment
    vars:
      - RAILS_ENV: production
    secrets: true
    run:
      - "true"
  - environment: staging
    type: gds
    app: dit-staging/staging-exopps/export-opportunities-worker-staging
    vars:
      - RAILS_ENV: production
    secrets: true
    run:
      - "true"
  - environment: production
    type: gds
    app: dit-services/exopps/export-opportunities-worker
    vars:
      - RAILS_ENV: production
    secrets: true
    run:
      - "true"