---
name: lite-licence-application
namespace: lite
scm: git@github.com:uktrade/lite-licence-application.git
environments:
  - environment: dev
    type: gds
    app: dit-staging/dev-lite/lite-licence-application-dev
    vars:
      - JAVA_EXTENSION: zip
      - NEXUS_PATH: lite-builds-raw/lite-licence-application/lite-licence-application
      - USE_NEXUS: true
      - PAAS_BUILDPACK: java_buildpack
    secrets: true
    run:
      - "true"
  - environment: uat
    type: gds
    app: dit-staging/uat-lite/lite-licence-application-uat
    vars:
      - JAVA_EXTENSION: zip
      - NEXUS_PATH: lite-builds-raw/lite-licence-application/lite-licence-application
      - USE_NEXUS: true
      - PAAS_BUILDPACK: java_buildpack
    secrets: true
    run:
      - "true"
  - environment: staging
    type: gds
    app: dit-staging/staging-lite/lite-licence-application-staging
    vars:
      - JAVA_EXTENSION: zip
      - NEXUS_PATH: lite-builds-raw/lite-licence-application/lite-licence-application
      - USE_NEXUS: true
      - PAAS_BUILDPACK: java_buildpack
    secrets: true
    run:
      - "true"
  - environment: prod
    type: gds
    app: dit-services/lite/lite-licence-application
    vars:
      - JAVA_EXTENSION: zip
      - NEXUS_PATH: lite-builds-raw/lite-licence-application/lite-licence-application
      - USE_NEXUS: true
      - PAAS_BUILDPACK: java_buildpack
    secrets: true
    run:
      - "true"
