---
name: lite-ogel-service
namespace: lite
scm: git@github.com:uktrade/lite-ogel-service.git
environments:
  - environment: dev
    type: gds
    app: dit-staging/dev-lite/lite-ogel-service-dev
    vars:
      - JAVA_EXTENSION: jar
      - NEXUS_PATH: lite-builds/uk/gov/bis/lite/lite-ogel-service
      - USE_NEXUS: true
      - PAAS_BUILDPACK: java_buildpack
    secrets: true
    run:
      - "true"
  - environment: uat
    type: gds
    app: dit-staging/uat-lite/lite-ogel-service-uat
    vars:
      - JAVA_EXTENSION: jar
      - NEXUS_PATH: lite-builds/uk/gov/bis/lite/lite-ogel-service
      - USE_NEXUS: true
      - PAAS_BUILDPACK: java_buildpack
    secrets: true
    run:
      - "true"
  - environment: staging
    type: gds
    app: dit-staging/staging-lite/lite-ogel-service-staging
    vars:
      - JAVA_EXTENSION: jar
      - NEXUS_PATH: lite-builds/uk/gov/bis/lite/lite-ogel-service
      - USE_NEXUS: true
      - PAAS_BUILDPACK: java_buildpack
    secrets: true
    run:
      - "true"
  - environment: prod
    type: gds
    app: dit-services/lite/lite-ogel-service
    vars:
      - JAVA_EXTENSION: jar
      - NEXUS_PATH: lite-builds/uk/gov/bis/lite/lite-ogel-service
      - USE_NEXUS: true
      - PAAS_BUILDPACK: java_buildpack
    secrets: true
    run:
      - "true"
