---
name: lite-ogel-registration
namespace: lite
scm: git@github.com:uktrade/lite-ogel-registration.git
environments:
  - environment: dev
    type: gds
    app: dit-staging/dev-lite/lite-ogel-registration-dev
    vars:
      - JAVA_EXTENSION: zip
      - NEXUS_PATH: lite-builds-raw/lite-ogel-registration/lite-ogel-registration
      - USE_NEXUS: true
      - PAAS_BUILDPACK: java_buildpack
    secrets: true
    run:
      - "true"
  - environment: uat
    type: gds
    app: dit-staging/uat-lite/lite-ogel-registration-uat
    vars:
      - JAVA_EXTENSION: zip
      - NEXUS_PATH: lite-builds-raw/lite-ogel-registration/lite-ogel-registration
      - USE_NEXUS: true
      - PAAS_BUILDPACK: java_buildpack
    secrets: true
    run:
      - "true"
  - environment: staging
    type: gds
    app: dit-staging/staging-lite/lite-ogel-registration-staging
    vars:
      - JAVA_EXTENSION: zip
      - NEXUS_PATH: lite-builds-raw/lite-ogel-registration/lite-ogel-registration
      - USE_NEXUS: true
      - PAAS_BUILDPACK: java_buildpack
    secrets: true
    run:
      - "true"
  - environment: prod
    type: gds
    app: dit-services/lite/lite-ogel-registration
    vars:
      - JAVA_EXTENSION: zip
      - NEXUS_PATH: lite-builds-raw/lite-ogel-registration/lite-ogel-registration
      - USE_NEXUS: true
      - PAAS_BUILDPACK: java_buildpack
    secrets: true
    run:
      - "true"
