---
name: lite-case-processing
namespace: lite
scm: git@github.com:uktrade/lite-case-processing.git
environments:
  - environment: dev
    type: gds
    app: dit-staging/dev-lite/lite-case-processing-dev
    vars:
      - JAVA_EXTENSION: zip
      - NEXUS_PATH: lite-builds-raw/lite-case-processing/lite-case-processing
      - USE_NEXUS: true
      - PAAS_BUILDPACK: java_buildpack
    secrets: true
    run:
      - "true"