---
name: navigator
namespace: enav
scm: git@github.com:uktrade/navigator.git
environments:
  - environment: dev
    type: gds
    app: dit-staging/dev-enav/enav-navigator-dev
    vars: []
    secrets: true
    run:
      - "npm install && npm rebuild node-sass && npm run build && rm -rf node_modules"
  - environment: staging
    type: gds
    app: dit-staging/staging-enav/enav-navigator-staging
    vars: []
    secrets: true
    run:
      - "npm install && npm rebuild node-sass && npm run build && rm -rf node_modules"
  - environment: production
    type: gds
    app: dit-services/enav/enav-navigator
    vars: []
    secrets: true
    run:
      - "npm install && npm rebuild node-sass && npm run build && rm -rf node_modules"
