---
name: staff-sso
namespace: datahub
scm: git@github.com:uktrade/staff-sso.git
environments:
  - environment: prod
    type: gds
    app: dit-services/datahub/staff-sso
    vars:
      - HERE: 1
    secrets: true
    run:
      - "true"
