---
name: trade-remedies-public
namespace: traderemedies
scm: git@github.com:uktrade/trade-remedies-public-ui.git
environments:
  - environment: dev
    type: gds
    app: dit-staging/dev-traderemedies/trade-remedies-public-dev
    vars: []
    secrets: true
    run:
      - "true"
  - environment: staging
    type: gds
    app: dit-staging/staging-traderemedies/trade-remedies-public-staging
    vars: []
    secrets: true
    run:
      - "true"
